In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image
import tensorflow.keras.backend as K
import numpy as np
import cv2
import sys
import glob
import os
from matplotlib import pyplot as plt
from pylab import rcParams
from tensorflow.keras.models import load_model
rcParams['figure.figsize'] = 15, 15



In [30]:
# load model
model = load_model('model_CAM.h5')


input_path = "C:/Users/Kaleem/EPFL/ZebrafishProject/Images/DataPNG/new_fssPNG/*.png"
output_path = "C:/Users/Kaleem/EPFL/ZebrafishProject/Images/DataPNG/new_fssPNGCAM/"

images = [(file) for file in glob.glob(input_path)]

#totalImages = len(images)
#print(totalImages)
#i = 0
for file in images:
    strIdx = 64
    print(file[strIdx:])
    img = image.load_img(file, target_size=(250, 500))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = x*(1./255)
    #x = preprocess_input(x)
   

    preds = model.predict(x)
    print(preds)
    class_idx = np.argmax(preds[0])
    #print(class_idx)
    class_output = model.output[:,class_idx]
    last_conv_layer = model.get_layer("block5_conv3")

    grads = K.gradients(class_output, last_conv_layer.output)[0]
    pooled_grads = K.mean(grads, axis=(0, 1, 2))
    iterate = K.function([model.input], [pooled_grads, last_conv_layer.output[0]])
    pooled_grads_value, conv_layer_output_value = iterate([x])
    for i in range(512):
        conv_layer_output_value[:, :, i] *= pooled_grads_value[i]

    heatmap = np.mean(conv_layer_output_value, axis=-1)
    heatmap = np.maximum(heatmap, 0)
    heatmap /= np.max(heatmap)

    img = cv2.imread(file)
    heatmap = cv2.resize(heatmap, (img.shape[1], img.shape[0]))
    heatmap = np.uint8(255 * heatmap)
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    superimposed_img = cv2.addWeighted(img, 0.6, heatmap, 0.4, 0)
    output_file = output_path+"Class_"+str(class_idx)+"_"+file[strIdx:]
    #print(output_file)
    cv2.imwrite(output_file, superimposed_img)


20190427_fss_fss1.png
[[8.6933011e-01 6.7391223e-04 4.7189192e-04 1.2952399e-01]]
20190427_fss_fss10.png
[[8.2595974e-01 5.5672339e-04 2.7110442e-04 1.7321248e-01]]
20190427_fss_fss11.png
[[8.3875471e-01 6.2461541e-04 2.9282644e-04 1.6032784e-01]]
20190427_fss_fss12.png
[[0.7483832  0.07211014 0.00288605 0.17662054]]
20190427_fss_fss13.png
[[9.7987533e-01 2.1036054e-04 1.4298603e-04 1.9771272e-02]]
20190427_fss_fss14.png
[[8.3875471e-01 6.2461541e-04 2.9282644e-04 1.6032784e-01]]
20190427_fss_fss15.png
[[8.3875471e-01 6.2461541e-04 2.9282644e-04 1.6032784e-01]]
20190427_fss_fss16.png
[[0.77451605 0.0025158  0.00098811 0.22198012]]
20190427_fss_fss17.png
[[0.68256843 0.00407245 0.00116895 0.31219015]]
20190427_fss_fss18.png
[[0.7908799  0.00177484 0.00103744 0.20630775]]
20190427_fss_fss19.png
[[9.1724336e-01 1.0923206e-02 4.4759113e-04 7.1385816e-02]]
20190427_fss_fss2.png
[[8.4736484e-01 9.1696979e-04 5.7259313e-04 1.5114558e-01]]
20190427_fss_fss20.png
[[0.7483832  0.07211014 0.00288

In [29]:
#img_path = 'C:/Users/Kaleem/EPFL/ZebrafishProject/Images/DataPNG/WildtypePNG/10L.png'
input_path = "C:/Users/Kaleem/EPFL/ZebrafishProject/Images/DataPNG/new_fssPNG/*.png"

print(input_path[64:])


*.png


In [ ]:
a = ['d','a','3']
type(model_1)
model_1.nas = a


In [ ]:
print(model_1.nas[0])

In [ ]:
preds = model.predict(x)
    

In [ ]:
print(preds)
class_idx = np.argmax(preds[0])

In [3]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    'C:/Users/Kaleem/EPFL/ZebrafishProject/Images/DataPNG/Preds/',
    target_size=(250, 500),
    batch_size=1,
    shuffle = False,
    class_mode='categorical')
predictions = model.predict_generator(test_generator, verbose=1)

Found 17 images belonging to 2 classes.
17/17 [==============================] - 38s 2s/step


In [ ]:
#print(predictions)
file_test = 'C:/Users/Kaleem/EPFL/ZebrafishProject/Images/DataPNG/Preds/4thPhenotypePNG/2_DAPT50ISC_1.png'
img_test = image.load_img(file_test, target_size=(250, 500))
x_test = image.img_to_array(img_test)
x_test = np.expand_dims(x_test, axis=0)
#x_test = preprocess_input(x_test)
x_test = x_test*(1./255)
#x_test = preprocess_input(x_test)
model.predict(x_test)


In [4]:
print(predictions)
#print(test_generator[0])
#print(x*(1./255))

[[9.9995387e-01 4.7248232e-06 1.1675329e-05 2.9627976e-05]
 [9.9993515e-01 6.2265767e-06 3.3270841e-05 2.5332469e-05]
 [9.9994659e-01 2.2773493e-06 4.3263612e-05 7.9240108e-06]
 [9.9825341e-01 6.6752604e-05 1.0437219e-03 6.3611008e-04]
 [9.9998724e-01 1.7890785e-06 3.5826627e-06 7.4401050e-06]
 [9.9992919e-01 1.3474129e-05 1.3367360e-05 4.3990607e-05]
 [9.9801338e-01 1.6266821e-04 9.5963763e-04 8.6428033e-04]
 [9.9998724e-01 1.2370327e-06 2.4228127e-06 9.1623751e-06]
 [9.9988699e-01 7.1973659e-06 5.3549953e-05 5.2293010e-05]
 [9.9995315e-01 6.5702684e-06 1.7249560e-05 2.2961553e-05]
 [9.9997580e-01 2.6253124e-06 7.2426528e-06 1.4301324e-05]
 [9.9997771e-01 3.0469262e-06 4.8126803e-06 1.4408970e-05]
 [9.9993634e-01 6.3955249e-06 1.0486754e-05 4.6763471e-05]
 [9.9958235e-01 4.1351261e-05 2.6947440e-04 1.0693967e-04]
 [9.9997044e-01 3.8087137e-06 6.4519450e-06 1.9265182e-05]
 [9.9579334e-01 6.2764139e-04 3.4332285e-03 1.4582442e-04]
 [6.8836169e-05 2.6927721e-02 1.0294640e-04 9.7290051e-0

In [ ]:
[[9.9995387e-01 4.7248232e-06 1.1675329e-05 2.9627976e-05]]
[[9.9993515e-01 6.2265767e-06 3.3270841e-05 2.5332469e-05]]
[[9.9994659e-01 2.2773493e-06 4.3263612e-05 7.9240108e-06]]
[[9.9825341e-01 6.6752604e-05 1.0437219e-03 6.3611008e-04]]
[[9.9998724e-01 1.7890785e-06 3.5826627e-06 7.4401050e-06]]
[[9.9992919e-01 1.3474129e-05 1.3367360e-05 4.3990607e-05]]
[[9.9801338e-01 1.6266821e-04 9.5963763e-04 8.6428033e-04]]
[[9.9998724e-01 1.2370327e-06 2.4228127e-06 9.1623751e-06]]
[[9.9988699e-01 7.1973659e-06 5.3549953e-05 5.2293010e-05]]
[[9.9995315e-01 6.5702684e-06 1.7249560e-05 2.2961553e-05]]
[[9.9997580e-01 2.6253124e-06 7.2426528e-06 1.4301324e-05]]
[[9.9997771e-01 3.0469262e-06 4.8126803e-06 1.4408970e-05]]
[[9.9993634e-01 6.3955249e-06 1.0486754e-05 4.6763471e-05]]
[[9.9958235e-01 4.1351261e-05 2.6947440e-04 1.0693967e-04]]
[[9.9997044e-01 3.8087137e-06 6.4519450e-06 1.9265182e-05]]
[[9.9579334e-01 6.2764139e-04 3.4332285e-03 1.4582442e-04]]